name: Deploy Hugo site

on:
  push:
    branches:
      - main
  workflow_dispatch:  # 👈 allow manual run

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.125.0'
        extended: true

    - name: Build Hugo
      run: hugo --minify --baseURL=https://far0w.github.io/shared_vademecum/

    - name: Add .nojekyll
      run: echo > public/.nojekyll

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public